---
- hosts: all
  user: root
  gather_facts: true

  vars:
   server_url: change.me
   admin_email: admin@change.me
   db_name: phpipam
   db_account: phpipam
   new_cert: false
   ansible_python_interpreter: /usr/bin/python3

  tasks:
    - set_fact:
        db_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
    - name: Install Prerequisites
      yum:
        name:
          [
            mariadb-server,
            nginx,
            php-curl,
            php-fpm,
            php-gd,
            php-gettext,
            php-gmp,
            php-intl,
            php-json,
            php-mbstring,
            php-mysqlnd,
            php-pear,
            php-recode,
            php-xmlrpc,
            php-xml
          ]
        update_cache: true
        state: present
    