---
- hosts: localhost
  user: gavin
  become: yes
  gather_facts: true

  vars:
   server_url: change.me
   admin_email: admin@change.me
   db_name: phpipam
   db_account: phpipam
   ipam_path: /var/www/html/ipam
   ansible_python_interpreter: /usr/bin/python3

  tasks:
    - set_fact:
        db_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
        db_root_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: Install Prerequisites...
      yum:
        name:
          [
            mariadb-server,
            nginx,
            php-curl,
            php-fpm,
            php-gd,
            php-gettext,
            php-gmp,
            php-intl,
            php-json,
            php-mbstring,
            php-mysqlnd,
            php-pear,
            php-recode,
            php-xmlrpc,
            php-xml
          ]
        update_cache: true
        state: present
   
    - name: Install Python MYSQL Module...
      pip:
        name: pymysql

    - name: Install PHP-IPAM
      git:
       repo: https://github.com/phpipam/phpipam.git
       dest:  /var/www/html/ipam
       version: 1.4

    - name: Copy Certificates...
      template:
       src: certs/ipam.{{item}}
       dest: /etc/ssl/ipam.{{item}}
      with_items:
       - crt
       - key

    - name: Replace NGINX Config File...
      template:
       src: templates/nginx.conf
       dest: /etc/nginx/nginx.conf

    - name: Update php-fpm Config File...
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: "www-data"
        replace: "nginx" 

    - name: Copy IPAM Config...
      copy:
        src: "{{ipam_path}}/config.dist.php"
        dest: "{{ipam_path}}/config.php"
  
    - name: Update IPAM Config File...
      replace:
        path: "{{ipam_path}}/config.php"
        regexp: "phpipamadmin"
        replace: "{{db_password}}"

    - name: Update IPAM Folder Permissions... 
      file:
        group: nginx
        owner: nginx
        recurse: yes
        path: "/var/www/html/ipam"
        state: directory
      
    - name: Firewall Permit HTTP(s)...
      firewalld:
        service: "{{item}}"
        permanent: yes
        state: enabled    
      with_items:
        - https
        - http

    - name: Enable SELinux Booleans...
      command: "setsebool -P {{item}} on"
      with_items:
        - httpd_can_network_connect


    - name: Start Services...
      service:
        name: "{{item}}"
        state: restarted
        enabled: yes
      with_items:
        - nginx
        - php-fpm
        - mariadb

    - name: Create Database...
      mysql_db:
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{db_name}}"
        state: present

    - name: Import Database...
      mysql_db:
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{db_name}}"
        state: import
        target: /var/www/html/ipam/db/SCHEMA.sql

    - name: Create Database User...
      mysql_user:
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present
        name: "{{db_account}}"
        password: "{{db_password}}"
        priv: "{{db_name}}.*:ALL"
        state: present
        sql_log_bin: no


