---
- hosts: localhost
  user: gavin
  become: yes
  gather_facts: true

  vars:
   server_url: change.me
   admin_email: admin@change.me
   db_name: phpipam
   db_account: phpipam
   ansible_python_interpreter: /usr/bin/python3

  tasks:
    - set_fact:
        db_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
    - name: Install Prerequisites...
      yum:
        name:
          [
            mariadb-server,
            nginx,
            php-curl,
            php-fpm,
            php-gd,
            php-gettext,
            php-gmp,
            php-intl,
            php-json,
            php-mbstring,
            php-mysqlnd,
            php-pear,
            php-recode,
            php-xmlrpc,
            php-xml
          ]
        update_cache: true
        state: present
   
    - name: Install Python MYSQL Module...
      pip:
        name: pymysql

 
    - name: Install PHP-IPAM
      git:
       repo: https://github.com/phpipam/phpipam.git
       dest:  /var/www/html/ipam
       version: 1.4


    - name: Update IPAM folder
      file:
        group: nginx
        owner: nginx
        recurse: yes
        path: "/var/www/html/ipam"
        state: directory

    - name: Copy Certificates...
      template:
       src: certs/ipam.{{item}}
       dest: /etc/ssl/ipam.{{item}}
      with_items:
       - crt
       - key

    - name: Replace NGINX Config File...
      template:
       src: templates/nginx.conf
       dest: /etc/nginx/nginx.conf

    - name: Update php-fpm Config File...
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: "www-data"
        replace: "nginx"      

    - name: Permit HTTP(s)...
      firewalld:
        service: "{{item}}"
        permanent: yes
        state: enabled    
      with_items:
        - https
        - http

